name: CI

on:
  push:
    branches: [main]

jobs:
  test:
    # ignore all-contributors PRs
    if: ${{ !contains(github.head_ref, 'all-contributors') }}

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [10, 12, 14, 16]

    steps:
    - name: Cancel previous runs
      uses: styfle/cancel-workflow-action@0.9.0

    - uses: actions/checkout@v2

    - name: Setup nodejs
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}
    - name: Install deps & validate
      run: npm run setup

  release:
    runs-on: ubuntu-latest

    steps:
    - name: Cancel previous runs
      uses: styfle/cancel-workflow-action@0.9.0

    - uses: actions/checkout@v2

    - name: Setup nodejs
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Install deps
      run: npm install
    - name: Build proj
      run: npm run build
    - name: Update tests, coverage, and release
      run: npm run test:update && npx codecov && npx semantic-release
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
